version: '3'

services:
  auth_server:
    image: my_php
    ports:
      - "8080:8080"
    volumes:
      - ./auth_server:/app
    command: php -S 0.0.0.0:8080 -t public

  resource_server:
    image: my_php
    ports:
      - "8081:8081"
    volumes:
      - ./resource_server:/app
    command: php -S 0.0.0.0:8081 -t public
